-- ============================================
-- 사하구청 AI 상담사 - Supabase 초기 설정
-- Supabase Dashboard > SQL Editor 에서 실행
-- ============================================

-- 1. pgvector 확장 활성화
create extension if not exists vector;

-- ============================================
-- 2. 벡터 검색용 테이블 (documents)
-- ============================================
create table if not exists documents (
  id text primary key,
  content text not null,
  embedding vector(384),
  metadata jsonb default '{}',
  created_at timestamp with time zone default now()
);

drop index if exists ix_documents_embedding;
create index ix_documents_embedding
  on documents using hnsw (embedding vector_cosine_ops);

drop index if exists ix_documents_metadata;
create index ix_documents_metadata
  on documents using gin (metadata);

-- ============================================
-- 3. 크롤링 원본 데이터 (raw_pages)
-- ============================================
create table if not exists raw_pages (
  id serial primary key,
  url text unique not null,
  title text,
  content text,
  category text,
  sub_category text,
  content_hash text,
  -- HTTP 조건부 GET용 캐시 검증자 (증분 크롤링에서 If-None-Match / If-Modified-Since로 전송)
  etag text,
  last_modified text,
  crawled_at timestamp with time zone default now(),
  last_checked_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 기존 테이블에 컬럼이 없을 경우를 위한 호환성 마이그레이션
alter table raw_pages add column if not exists etag text;
alter table raw_pages add column if not exists last_modified text;
alter table raw_pages add column if not exists last_checked_at timestamp with time zone default now();
-- 게시물 첨부파일 목록 [{"name","url"}] (JSONB)
alter table raw_pages add column if not exists attachments jsonb default '[]'::jsonb;
-- 원문 구조 재처리용 HTML. 일반 사용자에게는 공개하지 않는다.
alter table raw_pages add column if not exists raw_html text;

create index if not exists ix_raw_pages_category on raw_pages(category);

-- 증분 크롤링 실행 이력
create table if not exists crawl_runs (
  id bigint generated by default as identity primary key,
  mode text not null default 'incremental',
  menu text,
  status text not null check (status in ('running', 'succeeded', 'failed')),
  new_count int not null default 0,
  updated_count int not null default 0,
  unchanged_count int not null default 0,
  deleted_count int not null default 0,
  error_message text,
  started_at timestamp with time zone default now(),
  finished_at timestamp with time zone
);

-- ============================================
-- 4. 정제된 청크 데이터 (processed_chunks)
-- ============================================
create table if not exists processed_chunks (
  chunk_id text primary key,
  url text not null,
  title text,
  content text,
  category text,
  sub_category text,
  chunk_index int,
  total_chunks int,
  service_type text,
  -- 담당 부서명 (LLM이 본문에서 추출, 미명시 시 NULL)
  department text,
  target_audience text,
  keywords text,
  has_deadline boolean default false,
  has_contact_info boolean default false,
  summary text,
  embedded boolean default false,
  -- 해당 청크가 속한 페이지의 첨부파일 목록 [{"name","url"}] (JSONB)
  attachments jsonb default '[]'::jsonb,
  created_at timestamp with time zone default now()
);

-- 기존 테이블 호환성 마이그레이션
alter table processed_chunks add column if not exists department text;
alter table processed_chunks add column if not exists attachments jsonb default '[]'::jsonb;

create index if not exists ix_chunks_category on processed_chunks(category);
create index if not exists ix_chunks_service_type on processed_chunks(service_type);
create index if not exists ix_chunks_department on processed_chunks(department);
create index if not exists ix_chunks_embedded on processed_chunks(embedded);
create index if not exists ix_chunks_url on processed_chunks(url);

-- ============================================
-- 4-1. 구청 제공 공식 예상질문 정답셋
-- ============================================
create table if not exists official_faq (
  id integer primary key,
  question text not null unique,
  approved_answer text not null,
  source_url text not null,
  category text not null default '기타',
  keywords jsonb not null default '[]'::jsonb,
  is_time_sensitive boolean not null default false,
  verified_at date,
  updated_at timestamp with time zone not null default now()
);

create index if not exists ix_official_faq_category on official_faq(category);

-- ============================================
-- 5. 대화 이력 (conversation_logs)
-- ============================================
create table if not exists conversation_logs (
  id serial primary key,
  session_id text not null,
  role text not null,
  content text not null,
  sources text,
  created_at timestamp with time zone default now()
);

create index if not exists ix_conv_session on conversation_logs(session_id);
create index if not exists ix_conv_session_created on conversation_logs(session_id, created_at);

-- ============================================
-- 6. RLS 정책 (anon: 읽기/대화 INSERT만, service role: 전체)
-- ============================================
-- service_role 키는 RLS를 항상 우회하므로 별도 정책 불필요.
-- 아래 정책은 anon 키 접근만 제한하기 위한 것.

alter table documents enable row level security;
alter table raw_pages enable row level security;
alter table processed_chunks enable row level security;
alter table conversation_logs enable row level security;
alter table crawl_runs enable row level security;
alter table official_faq enable row level security;

-- documents: 챗봇 검색을 위한 SELECT만 허용
drop policy if exists "documents_anon_select" on documents;
create policy "documents_anon_select" on documents
  for select to anon using (true);

-- raw_pages: anon 접근 차단 (관리자 작업 전용)
drop policy if exists "raw_pages_anon_no_access" on raw_pages;
-- (policy 미생성 = anon 접근 불가)

-- processed_chunks: 챗봇이 키워드/카테고리 조회용으로 SELECT 가능
drop policy if exists "processed_chunks_anon_select" on processed_chunks;
create policy "processed_chunks_anon_select" on processed_chunks
  for select to anon using (true);

drop policy if exists "official_faq_anon_select" on official_faq;
create policy "official_faq_anon_select" on official_faq
  for select to anon, authenticated using (true);

revoke insert, update, delete on official_faq from anon, authenticated;
grant select on official_faq to anon, authenticated;

-- conversation_logs:
--   - 서명 쿠키의 session_id는 PostgreSQL이 직접 검증할 수 없으므로 anon 정책을
--     만들지 않는다. 모든 대화 이력 처리는 백엔드의 service_role을 통해서만 수행한다.
--   - anon에 using(true)를 허용하면 공개 anon 키만으로 모든 사용자의 대화를 조회하거나
--     삭제할 수 있으므로 절대 허용하지 않는다.
drop policy if exists "conv_anon_insert" on conversation_logs;
drop policy if exists "conv_anon_select" on conversation_logs;
drop policy if exists "conv_anon_delete" on conversation_logs;
-- 정책 미생성 = anon의 INSERT/SELECT/UPDATE/DELETE 모두 차단

-- ============================================
-- 7. 유사도 검색 함수
-- ============================================
-- search_path 고정으로 SECURITY DEFINER 권한 상승 공격 방지
-- (Supabase Security Advisor: Function Search Path Mutable)
create or replace function public.match_documents(
  query_embedding vector(384),
  match_count int default 5,
  filter_metadata jsonb default '{}'
)
returns table (
  id text,
  content text,
  metadata jsonb,
  similarity float
)
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
begin
  return query
  select
    d.id,
    d.content,
    d.metadata,
    1 - (d.embedding <=> query_embedding) as similarity
  from documents d
  where case
    when filter_metadata = '{}'::jsonb then true
    else d.metadata @> filter_metadata
  end
  order by d.embedding <=> query_embedding
  limit match_count;
end;
$$;

-- 함수 실행 권한을 anon/authenticated에만 명시적으로 부여 (public 회수)
revoke all on function public.match_documents(vector, int, jsonb) from public;
grant execute on function public.match_documents(vector, int, jsonb) to anon, authenticated;
