-- 운영 DB 1회 적용: 대화 이력 비공개 + 증분 크롤링 감사 이력
alter table public.conversation_logs enable row level security;
drop policy if exists "conv_anon_insert" on public.conversation_logs;
drop policy if exists "conv_anon_select" on public.conversation_logs;
drop policy if exists "conv_anon_delete" on public.conversation_logs;
revoke all on table public.conversation_logs from anon;

alter table public.raw_pages
  add column if not exists last_checked_at timestamp with time zone default now();

create table if not exists public.crawl_runs (
  id bigint generated by default as identity primary key,
  mode text not null default 'incremental',
  menu text,
  status text not null check (status in ('running', 'succeeded', 'failed')),
  new_count int not null default 0,
  updated_count int not null default 0,
  unchanged_count int not null default 0,
  deleted_count int not null default 0,
  error_message text,
  started_at timestamp with time zone default now(),
  finished_at timestamp with time zone
);
alter table public.crawl_runs enable row level security;
revoke all on table public.crawl_runs from anon;

-- 변경 페이지 처리 큐: service_role을 사용하는 Worker만 접근한다.
create table if not exists public.ingestion_jobs (
  id bigint generated by default as identity primary key,
  url text not null unique,
  category text,
  status text not null default 'queued'
    check (status in ('queued', 'running', 'succeeded', 'failed')),
  attempts int not null default 0,
  error_message text,
  discovered_at timestamp with time zone default now(),
  started_at timestamp with time zone,
  finished_at timestamp with time zone
);
create index if not exists ix_ingestion_jobs_status_discovered
  on public.ingestion_jobs(status, discovered_at);
alter table public.ingestion_jobs enable row level security;
revoke all on table public.ingestion_jobs from anon;

-- 같은 URL이 다시 변경되면 완료된 작업도 queued 상태로 되돌린다.
create or replace function public.enqueue_ingestion_job(
  job_url text,
  job_category text default null
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare
  result_id bigint;
begin
  insert into public.ingestion_jobs(url, category, status, attempts, error_message, discovered_at,
                                    started_at, finished_at)
  values (job_url, job_category, 'queued', 0, null, now(), null, null)
  on conflict (url) do update set
    category = excluded.category,
    status = 'queued',
    attempts = 0,
    error_message = null,
    discovered_at = now(),
    started_at = null,
    finished_at = null
  returning id into result_id;
  return result_id;
end;
$$;
revoke all on function public.enqueue_ingestion_job(text, text) from public, anon, authenticated;
grant execute on function public.enqueue_ingestion_job(text, text) to service_role;
